---
format:
  quarto-cv-pdf: default
author: Jacob Widaeus | CV
date: last-modified
phone: 070 - 755 25 14
address: "August Wahlströms väg 11, Danderyd"
email: Jacob.Widaeus@gmail.com
fontsize: 11pt
orcid: 0000-0002-3148-2829
#github: Widaeus
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: publikationer.json
  preprint: PREPRINT.json
validate-yaml: false
csl: ieee.csl
---
# Utbildning

*Karolinska Institutet*, Läkarexamen \hfill 2022

Examensarbete: High risk serological profile for autoimmunity in Antiphopspholipid syndrome - A retrospective single-centre cohort study, 2014-2020

\
*Sophiahemmet Högskola*, Sjuksköterskeprogrammet \hfill Jan. 2016 - Jan. 2017

Kurser i omvårdnadsvetenskap och basal fysiologi

\
*Danderyds Gymnasium*, Internationell Ekonomi \hfill Aug. 2011 - Juni 2014

Med kompletterande naturvetenskapliga kurser via NTI-skolan Mars 2015 - Dec. 2016

# Arbetslivserfarenhet

*Danderyds sjukhus AB*

AT-läkare \hfill Maj 2023 - Dec. 2024

Allmäntjänstgöring på Danderyds Sjukhus med vårdcentralstjänstgöring på Husläkarna i Österåker

\
Underläkare - Hjärtkliniken \hfill Juni 2022 - Maj 2023

Arbete på vårdavdelning, akutmottagning inkl jourverksamhet samt dagvård och inskrivningsmottagning för angiografi och pacemakeroperation

\
Underläkare - Neurologkliniken \hfill Juni 2021 - Maj 2022

Sommarvikariat 2021 och löpande timvikariat under HT-21 och VT -22

\
Undersköterska \hfill Aug. 2016 - Maj 2021

* Intensivvårdsavdelningen IVA
* Hjärtintensivvårdsavdelning HIA
* Avd 75 IMA
* Avd 77 AVA
* Avd 74 Lungmedicin
* MandoMeter AB - Slutenvårdsklinik för ätstörningssjukdom
* Aleris Omsorg AB - Äldre- och demensboende

\newpage

# Pedagogiska meriter

Amanuens i larmsimulering för termin 10 läkarstudenter \hfill 23 Maj 2024

\
Nominering för pedagogiskt pris, Karolinska Institutet - Danderyds Sjukhus

* 19 Januari 2024
* 13 Januari 2023

\
Lärare i katastrofmedicinsk simulering, Karolinska institutet \hfill 10 Jan 2023

\
Amanuens - Trombos och Hemostas \hfill Okt. 2020 - Jan. 2021

Kursamanuens för studentvald kurs på läkarprogrammet på Karolinska institutet för studenter termin 6

\
Studentsällskapet för Kirurgi och Anestesi på Karolinska Institutet \hfill Sep. 2019 - Sep. 2021

Styrelseledamot och amanuens i praktiska övningar

# Forskningsarbete
## Publikationer

::: {#refs-peer}
:::

## Pre prints

::: {#refs-preprint}
:::

# Referenser

Lämnas på förfrågan. 